version: "3"
services:
  consigne:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    container_name: consigne
    env_file: ./api/.env.dev
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./api/volume:/app/volume
      - ./api/configs.yaml:/app/configs.yaml
    entrypoint:
      ["sanic", "asgi:app", "--host=0.0.0.0", "--port=8000", "--workers", "4", "--no-motd"]
    depends_on:
      db:
        condition: service_healthy

  memcached:
    image: memcached:latest
    ports:
      - 127.0.0.1:11211:11211
    restart: always
  
  db:
    image: postgres:17.5
    env_file: ./api/.env.dev
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    volumes:
      - ./api/database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./api/database/psql_schema.sql:/home/psql_schema.sql
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "[ -r /var/run/postgresql/ready ] || ( pg_isready && touch /var/run/postgresql/ready)" ]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    build:
      dockerfile: ./front/Dockerfile
      context: .
    ports:
    - 127.0.0.1:8123:8080
    restart: always
    entrypoint:
      [ "http-server", "dist" ]
    depends_on:
      db:
        condition: service_healthy
      consigne:
        condition: service_started

volumes:
  pg_data:
    driver: local